site_name: "mailcow: dockerized documentation"
edit_uri: "https://github.com/mailcow/mailcow-dockerized-docs"
repo_url: https://github.com/mailcow/mailcow-dockerized
remote_branch: gh-pages
theme: material
markdown_extensions:
  - codehilite(guess_lang=true)
  - toc(permalink=true)
  - admonition
  - pymdownx.magiclink
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
pages:
- 'Information & Support': 'index.md'
- 'Prerequisites':
  - 'Prepare Your System': 'prerequesite-system.md'
  - 'DNS Setup': 'prerequesite-dns.md'
- 'Migrating from mailcow 0.14': 'migrate-mc014.md'
- 'Installation & Update':
  - 'Installation': 'install.md'
  - 'Update': 'install-update.md'
- 'First Steps (optional)':
  - 'SSL': 'firststeps-ssl.md'
  - 'Rspamd Web UI': 'firststeps-rspamd_ui.md'
  - 'Reverse Proxy': 'firststeps-rp.md'
  - 'Setup a relayhost': 'firststeps-relayhost.md'
  - 'Log to Syslog': 'firststeps-syslog.md'
  - 'Local MTA on Docker host': 'firststeps-local_mta.md'
  - 'Sender and receiver model': 'firststeps-sender_rcv.md'
- 'Debugging & Troubleshooting':
    - 'Introduction': debug.md
    - 'Logs': 'debug-logs.md'
    - 'Attach a Container': 'debug-attach_service.md'
    - 'Reset Passwords': 'debug-reset_pw.md'
    - 'Remove Persistent Data': 'debug-rm_volumes.md'
    - 'Common Problems': 'debug-common_problems.md'
- 'Usage & Examples':
  - 'mailcow UI':
      - 'Configuration': 'u_e-mailcow_ui-config.md'
      - 'Blacklist / Whitelist': 'u_e-mailcow_ui-bl_wl.md'
      - 'Spamfilter': 'u_e-mailcow_ui-spamfilter.md'
      - 'Temporary email aliase': 'u_e-mailcow_ui-spamalias.md'
      - 'Tagging': 'u_e-mailcow_ui-tagging.md'
      - 'Two-Factor Authentication': 'u_e-mailcow_ui-tfa.md'
  - 'Postfix':
      - 'Anonymize Headers': 'u_e-postfix-anonym_headers.md'
      - 'Disable Sender Addresses Verification': 'u_e-postfix-disable_sender_verification.md'
  - 'Dovecot':
      - "Expunge a User's Mails": 'u_e-dovecot-expunge.md'
      - 'More Examples with DOVEADM': 'u_e-dovecot-more.md'
  - 'Redis': 'u_e-redis.md'
  - 'Rspamd': 'u_e-rspamd.md'
  - 'Docker':
      - 'Customize Dockerfiles': 'u_e-docker-cust_dockerfiles.md'
      - 'Docker Compose Bash Completion': 'u_e-docker-dc_bash_compl.md'
  - 'Why bind9?': 'u_e-why_bind9.md'
  - 'Backup & Restore':
      - 'Backup Maildir': 'u_e-backup_restore-maildir.md'
      - 'MySQL': 'u_e-backup_restore-mysql.md'
  - 'Autodiscover / Autoconfig': 'u_e-autodiscover_config.md'
  - 'Redirect HTTP to HTTPS': 'u_e-80_to_443.md'
  - 'Adjust Service Configurations': 'u_e-change_config.md'
  - 'Deinstall': 'u_e-deinstall.md'
- 'Third party apps':
  - 'Roundcube': 'third_party-roundcube.md'
  - 'Portainer': 'third_party-portainer.md'
  - 'Gogs': 'third_party-gogs.md'
extra:
  logo: 'images/logo.svg'
  palette:
    primary: 'indigo'
    accent: 'orange'
extra_css: [extra.css]
